### ISSUE TITLE
Assistance on Script

### ISSUE THREAD

**Issue by zerofelero** [Gorlem/ScriptIt#53]
Hello!

I previously utilized the [Macro / Keybind Mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275039-macro-keybind-mod?) 1.12.2 and earlier, but now its no longer maintained, so I am looking for an alternative. Is it possible to utilize the following script with this mod? I know how to do everything except the auto respawn aspect utilizing this mod.

Script:
*$${IF(autousing);LOG("&2[Macro] &fAuto-Respawn Stopped.");UNSET(autousing);ECHO("/ps set drophead off");ECHO("/diff 1");STOP();ELSE;LOG("&2[Macro] &fAuto-Respawn Started.");SET(autousing);ECHO("/ps set drophead on");ECHO("/diff 10");DO;IF(HEALTH <= 1);WAIT(40t);RESPAWN();ENDIF;WAIT(20t);LOOP;ENDIF;}$$    

Thank you!

**Comment by Gorlem** [comment]
Hey,

This mod is still pretty much work-in-progress.
I wouldn't recommend you to use it yet.
